export const enum RouterString{
   DASHBOARD =  'dashboard',
   SIBILINGS =  'siblings',
   FEES =  'fees',
   STUDENTS =  'students',
   PARENTS =  'parents',
   AUTH =  'auth',
   BUSROUTE = 'busRoute',
   ADDRESS = 'address',
   LOGOUT = 'logout',
   SETTINGS = 'settings',
   LOGIN ='login',
   REGISTER = 'register',
   FORGETPASSWORD = 'forgetpassword',
   TENURECONFIG='tenureConfig',
   ORGCONFIG = 'orgConfig',
   USERCONFIG = 'userConfig',
   CONTAINER = 'pages',
   CLASSCONFIG = 'classConfig',
   ROLECONFIG = 'roleConfig',
   FEESCOMPONENTCONFIG ='feesComponentsConfig'
}